### ISSUE TITLE
Issues while Install workload healthservice on AKS clusters

### ISSUE THREAD

**Issue by kumarakshay01** [Azure/Mission-Critical-Online#1275]
Hi Team,

While running the E2E pipeline i am constantly stuck on this error - I have tried with multiple subscriptions and pipelines.

**Error**
/usr/bin/az account set --s
/usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command . '/home/vsts/work/_temp/azureclitaskscript1707118357002.ps1'
==> Linting src/app/charts/healthservice
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, 0 chart(s) failed
**************************** REGION: uksouth ****************************
*** Using Azure Region display name UK South
*** Load credentials for AKS Cluster aka15fad5-uksouth-aks in aka15fad5-stamp-uksouth-rg
WARNING: Merged "aka15fad5-uksouth-aks-admin" as current context in /home/vsts/.kube/config
*** Retrieved container image name from artifact - aka15fad5globalcr.azurecr.io/alwayson/healthservice:main-69
*** Retrieved Ingress Controller FQDN aka15fad5-cluster.uksouth.cloudapp.azure.com for AKS cluster aka15fad5-uksouth-aks
*** Retrieved Key Vault name aka15fad5-uksouth-kv
*** Retrieved the names of 14 secrets in Key Vault aka15fad5-uksouth-kv
*** Deploy healthservice to aka15fad5-uksouth-aks (in aka15fad5-stamp-uksouth-rg) via helm chart
Release "healthservice-workload" does not exist. Installing it now.
NAME: healthservice-workload
LAST DEPLOYED: Mon Feb  5 07:32:50 2024
NAMESPACE: workload
STATUS: deployed
REVISION: 1
TEST SUITE: None
error: error parsing jsonpath {..status.conditions[?(@.type==\"Ready\")].status}, unterminated filter
Certificate for workload-ingress-secret not ready. Waiting for 60 seconds and retrying... 1/30
error: error parsing jsonpath {..status.conditions[?(@.type==\"Ready\")].status}, unterminated filter
Certificate for workload-ingress-secret not ready. Waiting for 60 seconds and retrying... 2/30
error: error parsing jsonpath {..status.conditions[?(@.type==\"Ready\")].status}, unterminated filter
Certificate for workload-ingress-secret not ready. Waiting for 60 seconds and retrying... 3/30
error: error parsing jsonpath {..status.conditions[?(@.type==\"Ready\")].status}, unterminated filter
Certificate for workload-ingress-secret not ready. Waiting for 60 seconds and retrying... 4/30
error: error parsing jsonpath {..status.conditions[?(@.type==\"Ready\")].status}, unterminated filter
Certificate for workload-ingress-secret not ready. Waiting for 60 seconds and retrying... 5/30
error: error parsing jsonpath {..status.conditions[?(@.type==\"Ready\")].status}, unterminated filter
Certificate for workload-ingress-secret not ready. Waiting for 60 seconds and retrying... 6/30
error: error parsing jsonpath {..status.conditions[?(@.type==\"Ready\")].status}, unterminated filter
Certificate for workload-ingress-secret not ready. Waiting for 60 seconds and retrying... 7/30
error: error parsing jsonpath {..status.conditions[?(@.type==\"Ready\")].status}, unterminated filter
Certificate for workload-ingress-secret not ready. Waiting for 60 seconds and retrying... 8/30
error: error parsing jsonpath {..status.conditions[?(@.type==\"Ready\")].status}, unterminated filter
Certificate for workload-ingress-secret not ready. Waiting for 60 seconds and retrying... 9/30
error: error parsing jsonpath {..status.conditions[?(@.type==\"Ready\")].status}, unterminated filter
Certificate for workload-ingress-secret not ready. Waiting for 60 seconds and retrying... 10/30
error: error parsing jsonpath {..status.conditions[?(@.type==\"Ready\")].status}, unterminated filter
Certificate for workload-ingress-secret not ready. Waiting for 60 seconds and retrying... 11/30
error: error parsing jsonpath {..status.conditions[?(@.type==\"Ready\")].status}, unterminated filter
Certificate for workload-ingress-secret not ready. Waiting for 60 seconds and retrying... 12/30

This count will go till 30 and after 30 minutes the agent will crash...any help is greatly appreciated.

**Comment by heoelri** [comment]
@kumarakshay01 I can reproduce the issue you've reported. Here's a sample from my environment. The certificate is there and ready:

```bash
kubectl get certificates -n workload
NAME                      READY   SECRET                    AGE
workload-ingress-secret   True    workload-ingress-secret   12m
```

The check we use in our pipeline works on my machine:

```bash
k get certificate workload-ingress-secret -n workload -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}'
True
```

But it seems like it's not working in the pipeline at the moment:

```bash
error: error parsing jsonpath {..status.conditions[?(@.type==\"Ready\")].status}, unterminated filter
Certificate for workload-ingress-secret not ready. Waiting for 60 seconds and retrying... 1/30
error: error parsing jsonpath {..status.conditions[?(@.type==\"Ready\")].status}, unterminated filter
Certificate for workload-ingress-secret not ready. Waiting for 60 seconds and retrying... 2/30
```
