### ISSUE TITLE
Appetite for Bicep Templates for Infra

### ISSUE THREAD

**Issue by MarcelMichau** [Azure/Mission-Critical-Online#240]
Hi there!

Firstly, thank you so much for putting together this reference implementation. It really is a huge wealth of splendid examples & provides an awesome baseline for custom reference implementations.

Is there any appetite to provide Bicep examples of the infrastructure? As this reference implementation is solely focused on Azure, it would be nice to further promote Bicep templates & showcase features such as [modules](https://docs.microsoft.com/en-us/azure/azure-resource-manager/bicep/modules) to use along with ACR.

**Comment by msimecek** [comment]
Closing as the question has been answered 7 days ago.

If further discussion is needed, feel free to reopen.
