### ISSUE TITLE
Global composite SLA calculation

### ISSUE THREAD

**Issue by harrchen88** [Azure/Mission-Critical-Online#428]
Is there any reason why Azure Container Registry which is part of the global infrastructure not included in the global composite SLA calculation?

**Comment by sebader** [comment]
already answered offline. But to summarize here: ACR is not a full runtime dependency. Once an image has been pulled on an AKS node, it gets cached there and is reused for starting new pods. Only when a new node gets added, it needs to connect to ACR again
