### ISSUE TITLE
`Clean-StaleResources.ps1` add error handling 

### ISSUE THREAD

**Issue by heoelri** [Azure/Mission-Critical-Online#534]
`Clean-StaleResources.ps1` should return an error or a warning when the resource prefix is wrong or no log analytics workspace (with this prefix exists). Instead of returning an error that the resource-group parameter is not set.

CC: @svgupta97

**Comment by svgupta97** [comment]
![c7c4faeb-42b3-4952-8ad0-7b2e62b880ad](https://user-images.githubusercontent.com/22669477/185388419-69fecbfe-9542-4971-b3b1-d0b7baf56516.jpg)
Seeing this error when running the script. Commenting the conversion to a hashtable fixes the issue.
