### ISSUE TITLE
Fail load test run when `$result.testResult` is `FAILED` instead of timeout

### ISSUE THREAD

**Issue by heoelri** [Azure/Mission-Critical-Online#535]
CC: @svgupta97

**Comment by heoelri** [comment]
@svgupta97 it might make sense to add your finding (register the load test provider) to the troubleshooting guide.

**Comment by svgupta97** [comment]
Here is the error message I received: 

```
VERBOSE: GET with 0-byte payload
VERBOSE: received 3725-byte response of content type application/json
VERBOSE: Content encoding: utf-8
*** Test Run X is in status FAILED
```

**Comment by heoelri** [comment]
@sebader FYI

**Comment by heoelri** [comment]
@svgupta97 would you mind raising a separate issue for the "load testing resource provider registration" issue with more details including the error message and/or a screenshot if possible?
