### ISSUE TITLE
Azure Load testing Pipeline error (standalone mode)

### ISSUE THREAD

**Issue by rishabhsaha** [Azure/Mission-Critical-Online#745]
When I try to run the azure load testing pipeline, it succeeds provisioning the azure load test service but fails with the following error int create test step.

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/12716801/206274172-1fb4e2a6-4004-416e-bb40-d3390c4f0002.png)

**Comment by heoelri** [comment]
Hi @rishabhsaha, thanks for reporting this issue. I'll take a look.
