### ISSUE TITLE
Import Sample Data & Test Stamp Endpoints

### ISSUE THREAD

**Issue by MrCirca** [Azure/Mission-Critical-Online#831]
Hello,
I try to run e2e environment in one region(northeurope only) . I run pipeline from **main** branch. I have 2 failures.

- Cannot import sample data
- Stamps endpoints fail.

`
/usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -Command . '/home/vsts/work/_temp/b8eda1b2-2129-4361-ad0e-be3ea344e25f.ps1'
*******************
*** SMOKE TESTS ***
*******************
*** Testing 1 targets
*** Testing stamp availability using e58e2efad5-cluster.northeurope.cloudapp.azure.com
*** Call - Stamp Health (stamp)
[GET] https://e58e2efad5-cluster.northeurope.cloudapp.azure.com/healthservice/health/stamp
{"lastExecution":"2023-02-08T14:18:58.0569895+00:00","checks":[{"component":"AzMonitorHealthScore","status":"Unhealthy","duration":"00:00:00.1136058"},{"component":"BlobStorage","status":"Unhealthy","duration":"00:00:00.1276586"},{"component":"Database","status":"Unhealthy","duration":"00:00:05.0364669"},{"component":"MessageProducer","status":"Unhealthy","duration":"00:00:00.0207653"}]}
WARNING: *** Request to https://e58e2efad5-cluster.northeurope.cloudapp.azure.com/healthservice/health/stamp failed. Retrying... 1/20
[GET] https://e58e2efad5-cluster.northeurope.cloudapp.azure.com/healthservice/health/stamp

`
Do i need some other configuration manually or edit pipeline?

**Comment by johnathon-b** [comment]
What branch are you running? Most recent main is failing.

What rights does your SPN have over the subscription?

**Comment by MrCirca** [comment]
I run main branch.  I think that azure service principal has admin rights.

**Comment by MrCirca** [comment]
Which branch is stable?

**Comment by johnathon-b** [comment]
I'm deploying #809 which is the last one to pass the repo tests.

I'm deploying in INT right now as I was having other issues deploying into INT. I'll let you know my results after my testing.

**Comment by johnathon-b** [comment]
I ran the e2e w/ that branch and initially had the same issue. I ran it one more time (deleting every resource) and it eventually got past the smoke screens.

Currently sitting at an issue where load balance testing is failing and I couldn't test Chaos in the region I am.

I'm unable to deploy INT because of the same error I am seeing in the e2e pipeline around the `AzureCLI@2` being pinned to `2.216.0`. 

`--auth-type key` isn't working with this version so I had to manually update the CLI for the tasks in e2e that used `az storage account`. Not sure if this is related but wanted to provide an update on my findings so far.

**Comment by MrCirca** [comment]
Any ideas?

**Comment by johnathon-b** [comment]
I just ran e2e on that #809 without chaos and load testing fine..

Once it destroys I am going to try main branch.

**Comment by johnathon-b** [comment]
INT is still broken due to an issue I am having with the Az.Storage which I reported here:
https://github.com/Azure/azure-cli/issues/25396

I am seeing some errors in the `Upload UI app to Blob` task but they don't trigger a pipeline failure and the app is still deployed.

**Comment by heoelri** [comment]
Hi @johnathon-b, Hi @MrCirca, thanks for bringing this up. We're not seeing this issue in our nightly INT runs. Can you share more details of what's happening?  The failed import of sample data is expected when the stamp endpoints are not working as expected. There are various potential reasons for that. One could be that cert-manager wasn't able to request certificates for the endpoint. We've documented some of the potential resons in our troubleshooting guide: https://github.com/Azure/Mission-Critical-Online/blob/main/docs/reference-implementation/Troubleshooting.md
