### ISSUE TITLE
Error when deploying - WorkloadIdentityAddonFeatureFlagNotEnabled

### ISSUE THREAD

**Issue by F-laolu** [Azure/Mission-Critical-Online#884]
**Failure sending request: StatusCode=0 -- Original Error: Code="WorkloadIdentityAddonFeatureFlagNotEnabled" Message="Azure AD Workload Identity is not allowed to enable since feature flag \"Microsoft.ContainerService/EnableWorkloadIdentityPreview\" is not registered.**

The error above whappened while following the how to guide. However, this documentation (https://learn.microsoft.com/en-us/azure/aks/workload-identity-deploy-cluster#register-the-enableworkloadidentitypreview-feature-flag) can be of help.

**Comment by sebader** [comment]
Thanks for reporting this! The feature should GA this month, so it's save to assume this preview registration should go away very soon. Hence I'm not sure it' still worth to add this to the doc?!

https://github.com/Azure/AKS/issues/1480#issuecomment-1452499002
