### ISSUE TITLE
Load Test Failing due to High Error Rate? 

### ISSUE THREAD

**Issue by nicolalgallacher** [Azure/Mission-Critical-Online#935]
Hi all, when running the E2E Mission critical pipeline the load test section seems to fail with "The Test was stopped due to high error rate" I've attached some screenshots as well. Is there anything in the configuration we can change to ensure it runs to completion? 

Thanks! 

![image](https://user-images.githubusercontent.com/64469836/232036404-85544322-1766-44ca-b724-ac7bff11eeb9.png)

![image](https://user-images.githubusercontent.com/64469836/232036468-f7e8b2e5-e7f0-402c-8c52-dc1f577167c9.png)

![image](https://user-images.githubusercontent.com/64469836/232036556-f1ab7592-cb6c-4bea-8821-5d8af499f7a5.png)

**Comment by nicolalgallacher** [comment]
Additional Load Testing Logs: 

![image](https://user-images.githubusercontent.com/64469836/232039826-85e21576-700a-464d-b857-f415fbe42d8b.png)
![image](https://user-images.githubusercontent.com/64469836/232039896-c8a5d610-9d37-4d00-9d98-1f8e0bb2ade7.png)

**Comment by sebader** [comment]
Thanks for opening the issue. We are aware of this. A while go Azure Load Testing changed their behavior to fail a test once a certain error rate within a timeframe is hit. We are in contact with that team as currently there is no way to influence that behavior.
@heoelri do you maybe have any news on this or could ping them again?

**Comment by nicolalgallacher** [comment]
Thanks for the update! Reduced the user threads from 500 to 50 in the .ado/pipelines/config/configuration.yaml and seems to allow it to complete so can work to reduce the number in the meantime but would be great to stay updated on if the Load Testing behaviour changes to allow larger failures

**Comment by sebader** [comment]
Azure Load Test just released a feature to control the failure rate for stopping a test. We'll look into incorporating this soon
https://learn.microsoft.com/en-us/azure/load-testing/how-to-define-test-criteria?tabs=portal#auto-stop-configuration

cc @heoelri

**Comment by sebader** [comment]
We finally got to update to the latest version of Azure Load Test. this is now resolved
