### ISSUE TITLE
"terraformoutputGlobalInfra" file doesn't exist.

### ISSUE THREAD

**Issue by NagaSwamy473** [Azure/Mission-Critical-Online#937]
Hi Team,

Getting an error while deploying the new stamp in an existing environment where Global and single stamp is already available and running.

The error is: 
Could not find "terraformoutputGlobalInfra" file doesn't exist.
Here I am trying to execute the ADO pipeline by selecting the deploy stamp infrastructure alone since we already have the environment at Global level. Attached the error screenshot link below.
![image](https://user-images.githubusercontent.com/131235082/232980660-f9be168e-1cc0-4add-9b0b-b5ced2ac5320.png)
Please help us to fix the issue.

**Comment by sebader** [comment]
Hi @NagaSwamy473, every time you run the pipeline from scratch, even if the targeted environment already exists, you need to run the two terraform deployment tasks (for global and for the regional release units). Terraform should not perform any changes but it will create the output file which is being needed by the subsequent tasks

**Comment by NagaSwamy473** [comment]
Ok thank you very much. So, I can run the pipeline by selecting the deploy global resources & deploy regional infrastructure tasks from pipeline.
I am asking this again because, we have our services already running with 1st stamp and our deployment in 2nd stamp should not impact that.

**Comment by sebader** [comment]
in most cases I would just run the pipeline with all the default tasks enabled. At a later point you will have more experience and know which tasks can optionally be skipped, depending on what you are trying to do. But to be on the save side: just dont change the default tasks for now

**Comment by NagaSwamy473** [comment]
ok, I tried deploying the new stamp but it is throwing an error related to frontdoor.tf terraform file.
Could you please help me with fixing this error.
Error: Duplicate object key
│ 
│   on frontdoor.tf line 166, in resource "azurerm_cdn_frontdoor_origin" "backendapi":
│  166:   for_each = { for index, backend in var.backends_BackendApis : backend.address => backend }
│     ├────────────────
│     │ backend.address is "10.0.236.154"
│ 
│ Two different items produced the key "10.0.236.154" in this 'for'
│ expression. If duplicates are expected, use the ellipsis (...) after the
│ value expression to enable grouping by key.
╵
##[error]Bash exited with code '1'.

**Comment by NagaSwamy473** [comment]
Hi Sabedar, Actually we are using the mission critical-connected/reference implementation and deployed the existing the environment with same repo. I am not sure how can we fix the error which we are getting with the frontdoor file while deploying the 2nd stamp. That is where I am looking for the help from our Github community.
